import { useMemo } from 'react';
import { type Vessel } from './ship-service';

/**
 * Hardcoded dataset extracted from USNI News Fleet and Marine Tracker: March 9, 2026.
 * Plotted in approximate regional coordinates. 
 */
const USNI_VESSELS: Vessel[] = [
    // Japan (Yokosuka)
    {
        mmsi: -1001,
        name: 'USS George Washington (CVN-73)',
        lat: 35.2923,
        lon: 139.6601,
        shipClass: 'military',
        isDistress: false,
        isMilitary: true,
        isDark: false,
        lastUpdate: Date.now(),
        destination: 'Yokosuka, Japan'
    },
    // Philippine Sea
    {
        mmsi: -1002,
        name: 'USS Tripoli (LHA-7)',
        lat: 18.0,
        lon: 130.0,
        shipClass: 'military',
        isDistress: false,
        isMilitary: true,
        isDark: false,
        lastUpdate: Date.now(),
    },
    {
        mmsi: -1003,
        name: 'USS San Diego (LPD-22)',
        lat: 18.1,
        lon: 130.1,
        shipClass: 'military',
        isDistress: false,
        isMilitary: true,
        isDark: false,
        lastUpdate: Date.now(),
    },
    {
        mmsi: -1004,
        name: 'USS New Orleans (LPD-18)',
        lat: 17.9,
        lon: 129.9,
        shipClass: 'military',
        isDistress: false,
        isMilitary: true,
        isDark: false,
        lastUpdate: Date.now(),
    },
    // Caribbean Sea
    {
        mmsi: -1005,
        name: 'USS Iwo Jima (LHD-7) ARG',
        lat: 15.0,
        lon: -75.0,
        shipClass: 'military',
        isDistress: false,
        isMilitary: true,
        isDark: false,
        lastUpdate: Date.now(),
    },
    {
        mmsi: -1006,
        name: 'USS Fort Lauderdale (LPD-28)',
        lat: 15.1,
        lon: -74.9,
        shipClass: 'military',
        isDistress: false,
        isMilitary: true,
        isDark: false,
        lastUpdate: Date.now(),
    },
    {
        mmsi: -1007,
        name: 'USS San Antonio (LPD-17)',
        lat: 14.9,
        lon: -75.1,
        shipClass: 'military',
        isDistress: false,
        isMilitary: true,
        isDark: false,
        lastUpdate: Date.now(),
    },
    {
        mmsi: -1008,
        name: 'USS Lake Erie (CG-70)',
        lat: 16.0,
        lon: -76.0,
        shipClass: 'military',
        isDistress: false,
        isMilitary: true,
        isDark: false,
        lastUpdate: Date.now(),
    },
    {
        mmsi: -1009,
        name: 'USS Wichita (LCS-13)',
        lat: 16.2,
        lon: -75.8,
        shipClass: 'military',
        isDistress: false,
        isMilitary: true,
        isDark: false,
        lastUpdate: Date.now(),
    },
    // Eastern Mediterranean
    {
        mmsi: -1010,
        name: 'USS Roosevelt (DDG-80)',
        lat: 34.0,
        lon: 33.0,
        shipClass: 'military',
        isDistress: false,
        isMilitary: true,
        isDark: false,
        lastUpdate: Date.now(),
    },
    {
        mmsi: -1011,
        name: 'USS Bulkeley (DDG-84)',
        lat: 34.1,
        lon: 33.2,
        shipClass: 'military',
        isDistress: false,
        isMilitary: true,
        isDark: false,
        lastUpdate: Date.now(),
    },
    {
        mmsi: -1012,
        name: 'USS Oscar Austin (DDG-79)',
        lat: 33.9,
        lon: 32.8,
        shipClass: 'military',
        isDistress: false,
        isMilitary: true,
        isDark: false,
        lastUpdate: Date.now(),
    },
    {
        mmsi: -1013,
        name: 'USS Thomas Hudner (DDG-116)',
        lat: 34.2,
        lon: 32.5,
        shipClass: 'military',
        isDistress: false,
        isMilitary: true,
        isDark: false,
        lastUpdate: Date.now(),
    },
    // Red Sea
    {
        mmsi: -1014,
        name: 'USS Gerald R. Ford (CVN-78) CSG',
        lat: 19.0,
        lon: 39.0,
        shipClass: 'military',
        isDistress: false,
        isMilitary: true,
        isDark: false,
        lastUpdate: Date.now(),
    },
    {
        mmsi: -1015,
        name: 'USS Winston S. Churchill (DDG-81)',
        lat: 19.1,
        lon: 39.1,
        shipClass: 'military',
        isDistress: false,
        isMilitary: true,
        isDark: false,
        lastUpdate: Date.now(),
    },
    {
        mmsi: -1016,
        name: 'USS Bainbridge (DDG-96)',
        lat: 18.9,
        lon: 38.9,
        shipClass: 'military',
        isDistress: false,
        isMilitary: true,
        isDark: false,
        lastUpdate: Date.now(),
    },
    {
        mmsi: -1017,
        name: 'USS Mahan (DDG-72)',
        lat: 19.2,
        lon: 38.8,
        shipClass: 'military',
        isDistress: false,
        isMilitary: true,
        isDark: false,
        lastUpdate: Date.now(),
    },
    // Persian Gulf
    {
        mmsi: -1018,
        name: 'USS Canberra (LCS-30)',
        lat: 26.2,
        lon: 51.5,
        shipClass: 'military',
        isDistress: false,
        isMilitary: true,
        isDark: false,
        lastUpdate: Date.now(),
    },
    {
        mmsi: -1019,
        name: 'USS Tulsa (LCS-16)',
        lat: 26.3,
        lon: 51.6,
        shipClass: 'military',
        isDistress: false,
        isMilitary: true,
        isDark: false,
        lastUpdate: Date.now(),
    },
    {
        mmsi: -1020,
        name: 'USS Santa Barbara (LCS-32)',
        lat: 26.1,
        lon: 51.4,
        shipClass: 'military',
        isDistress: false,
        isMilitary: true,
        isDark: false,
        lastUpdate: Date.now(),
    },
    // Arabian Sea
    {
        mmsi: -1021,
        name: 'USS Abraham Lincoln (CVN-72) CSG',
        lat: 15.0,
        lon: 65.0,
        shipClass: 'military',
        isDistress: false,
        isMilitary: true,
        isDark: false,
        lastUpdate: Date.now(),
    }
];

export function useUSNIShips() {
    const usniVessels = useMemo(() => USNI_VESSELS, []);
    return { usniVessels };
}
